### ISSUE TITLE
example

### ISSUE THREAD

**Issue by rveltz** [spacedome/FEASTSolver.jl#1]
Hi,

Can you provide a working example of `feast!` please?

Thank you

**Comment by spacedome** [comment]
Sure! Here is an example computing the 10 smallest eigenvalues of a discrete lapacian.

```julia
A = diagm(-1 => fill(-1.0, 99), 0 => fill(2.0, 100), 1 => fill(-1.0, 99))
C, R = complex(0.05, 0.0), 0.05 # contour
X = rand(ComplexF64, 100, 20) # initial subspace

e, v, res = feast!(X, A, c=C, r=R, nodes=8, debug=true, ϵ=10e-15)
```
I also put this example in `test/feast.jl` so you could run it from there.

The linear `feast!` methods might be a bit buggy at the moment, I've been using this repo for some research with nonlinear feast, and its all a bit of a mess now, should get around to rewriting it soon.

**Comment by rveltz** [comment]
thank you

**Comment by rveltz** [comment]
I forgot to ask if the contour can only be circular?

**Comment by spacedome** [comment]
Right now I only have implemented circular contours with trapezoidal quadratures. I can implement elliptical or general contours if you need that, I just hadn't gotten around to it yet.

The feast fortran code supports general contours, is a bit faster, and you can call it somewhat easily from Julia with a ccall (I have code for this somewhere if you need it).

**Comment by rveltz** [comment]
I am interested in rectangular contours. I want to try feast against Shift-Invert method to see I can compute some eigenelements faster.

**Comment by spacedome** [comment]
I should be able to add this sometime next week, I opened a new issue for it #2

**Comment by rveltz** [comment]
Thanks a lot!

**Comment by rveltz** [comment]
Hi, any progress on this?

**Comment by spacedome** [comment]
Yes, it turned into a bigger refactoring than I thought, probably will commit it today.

**Comment by rveltz** [comment]
Thank you!

**Comment by spacedome** [comment]
Just added rectangular contours, I added a `Contour` type, only the `feast!` method has been rewritten to use it so far. I'm still doing a large rewrite/refactor, but the `Contour` and `feast!` interfaces should remain the same.

A rectangular contour will have worse convergence properties than a circular one, and I am not particularly confident in my implementation of the quadratures, though they should be usable at least. I have trapezoidal and gauss-legendre rectangle implementations that worked on some simple test problems. It is also possible to do fancy things like conformally mapping a circle onto a rectangle, which I have not done, but have references if you are interested in trying other quadratures. Custom shapes are possible too.

Here is an example, on this problem gauss/rectangle is only slightly worse than trapezoidal/circle
```
A = diagm(-1 => fill(-1.0, 99), 0 => fill(2.0, 100), 1 => fill(-1.0, 99))
C, R = complex(0.05, 0.0), 0.05 # contour
X = rand(ComplexF64, 100, 20) # initial subspace

# contour = circular_contour_trapezoidal(C, R, 16)
# contour = rectangular_contour_trapezoidal(0.0 - R*im, 2*R + R*im, 16)
contour = rectangular_contour_gauss(0.0 - R*im, 2*R + R*im, 16)

e, v, res = feast!(X, A, contour, debug=true, ϵ=10e-15)
```

**Comment by rveltz** [comment]
That's super cool!!

**Comment by rveltz** [comment]
I have two questions:
- how can I make it work with `A` sparse matrix?
- am I making a mistake? To me the computed eigenvalues does not belong to the rectangle:

```
N = 100
A = I + sprand(N,N,0.1)
C, R = complex(0.05, 0.0), 0.05 # contour
X = rand(ComplexF64, N, 20) # initial subspace

# contour = circular_contour_trapezoidal(C, R, 16)
# contour = rectangular_contour_trapezoidal(0.0 - R*im, 2*R + R*im, 16)
contour = rectangular_contour_gauss(0.0 - R*im, 2*R + R*im, 16)
contour = rectangular_contour_gauss(0.9 - R*im, 1.1 + R*im, 16)

e, v, res = feast!(X, Array(A), contour, debug=true, ϵ=10e-15)

e1, = eigen(Array(A))

println("--> EV from FEAST")
Base.display(e)
```

gives

```
--> EV from FEAST
5-element Array{Complex{Float64},1}:
 0.9671143464578497 + 0.20778947984445004im   
  0.967114346460329 - 0.20778947984199284im   
 0.9966306757802081 + 0.4371201851269825im    
 0.9966306799246172 - 0.4371201799422821im    
 1.0328617488474454 + 1.5984691646813154e-16im
```

**Comment by spacedome** [comment]
It should work with sparse now, I was using `lu!` to save memory allocation, but this does not work for sparse. Saving the factorizations between iterations gives a large performance improvement, but is memory expensive.

There was a bug in my code to check when an eigval is in the rectangle, it only checked along the real axis, should be fixed now.

Also, I have added a utility method to display the results of `feast!`, mostly useful when there are spurious eigvals.
```
convergence_info(e,v,res,contour)
---------------------------------------->
Number of eigenvalues inside contour: 1
Number inside converged : 1
Max res inside: 1.1315192903308862e-15
Max res inside non spurious: 1.1315192903308862e-15
```

**Comment by rveltz** [comment]
Thank you!
